version: "3.8"

services:
  mongodb:
    image: mongo:5
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db

  server:
    image: devopsacademyv1/backend:latest
    restart: always
    ports:
      - "${SERVER_PORT:-5000}:5000"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - mongodb

  client:
    image: devopsacademyv1/frontend:latest
    restart: always
    ports:
      - "${CLIENT_PORT:-3000}:80"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - server

volumes:
  mongo_data:
